FROM node:20-alpine

WORKDIR /app

COPY . .

RUN npm install

ARG NEXT_PUBLIC_CMS_API_BASE_URL
ARG NEXT_PUBLIC_EDITECH_API_BASE_URL
ARG NEXT_PUBLIC_EDITECH_X_USERNAME
ARG NEXT_PUBLIC_EDITECH_X_PASSWORD
ARG NEXT_PUBLIC_EDITECH_TOKEN

ENV NEXT_PUBLIC_CMS_API_BASE_URL=$NEXT_PUBLIC_CMS_API_BASE_URL
ENV NEXT_PUBLIC_EDITECH_API_BASE_URL=$NEXT_PUBLIC_EDITECH_API_BASE_URL
ENV NEXT_PUBLIC_EDITECH_X_USERNAME=$NEXT_PUBLIC_EDITECH_X_USERNAME
ENV NEXT_PUBLIC_EDITECH_X_PASSWORD=$NEXT_PUBLIC_EDITECH_X_PASSWORD
ENV NEXT_PUBLIC_EDITECH_TOKEN=$NEXT_PUBLIC_EDITECH_TOKEN

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
